accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name="create"),
    # 키를 받기위해서 int:pk사용
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    #라우트하는 과정+primary key를 적어줘야함
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

winwin_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),    #127.~~~/a
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

# null = false 이유는 텍스트가하나밖에없어서 다 사라질수도 있다잉

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 유저네임 필드를 비활성화
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld


# 로그인여부를하고 리다이렉트까지 해줌...!!! 원래짰었던 /accounts/login/ 장고 기본주소이기때문에
@login_required(login_url=reverse_lazy('accountapp:login'))
def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get("hello_world_input")

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        # hello_world_list = HelloWorld.objects.all()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    # return render(request, 'accountapp/hello_world.html',
    #               context={'hello_world_list': hello_world_list})
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html',
                      context={'hello_world_list': hello_world_list})
    # context={'text': 'get method!'})


# def hello_world(request):
#     return render(request, 'accountapp/hello_world.html')


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = "target_user"
    template_name = 'accountapp/detail.html'


#     연결 라우팅을 해줘야한다!!

has_ownership = [login_required, account_ownership_required]


@method_decorator(has_ownership, 'post')
@method_decorator(has_ownership, 'get')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = "target_user"

    # success_url = reverse_lazy("accountapp:hello_world")

    template_name = 'accountapp/update.html'


    def get_success_url(self):
        # user을 안찾아가도됨!!
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})

    # # 함수가아니라 클래스안에 메소드임으로 데코레이터자체를 사용하지못한다..!!클래스 데코 , 변환코드
    #
    # def get(self, request, *args, **kwargs):
    #
    #     # get_object 는 타겟 오브젝트랑 똑같음...!!
    #
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #
    #         # 부모메소드 겟해줌
    #
    #         return super().get(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    # def post(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #
    #         # 부모메소드 겟해줌
    #
    #         return super().post(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

    # def get(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #         # 부모메소드 겟해줌
    #         return super().get(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #
    #             # HttpResponseRedirect(reverse('accountapp:login'))
    #
    # def post(self, request, *args, **kwargs):
    #     if request.user.is_authenticated and self.get_object() == request.user:
    #         # 부모메소드 겟해줌
    #         return super().post(request, *args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>sing up</h4>
        </div>

        <div>
            <form action="{% url 'accountapp:create' %}" method='post'>
                {% csrf_token %}

                {% bootstrap_form form %}


                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
            </form>

        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>DELETE INFO</h4>
        </div>

        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method='post'>
                {% csrf_token %}

                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
            </form>

        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image">
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                           class="material-icons round_button">
                            edit
                        </a>
                    {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
                <h2>
                    <a href="{% url 'profileapp:create' %}">
                        create profile
                    </a>
                </h2>
            {% endif %}

            </h2>
        </div>

        <div>
{#            {{ target_user.date_joined }}#}
        </div>


        {% if user == target_user %}

            <div>
                <a href="{% url 'accountapp:update' pk=target_user.pk %}"
                   class="material-icons round_button mx-2">
                    settings
                </a>

                <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
                   class="material-icons round_button mx-2">
                    close
                </a>
            </div>

            {#            이름을 그대러 써주면 아이콘이 그대로 생성이 된다..!! 부트스트랩 마진 mx-4도 넣어줌 #}

        {% endif %}

    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    {#    <style>#}
    {##}
    {#    .testing{#}
    {#        background-color: yellow;#}
    {#        height: 40px;#}
    {#        width: 40px;#}
    {#        margin: 2rem;#}
    {#        border-radius: .5rem;#}
    {#    }#}
    {#    </style>#}

    {#    <div style="margin: 2rem; overflow: scroll;">#}
    <div style="margin: 2rem; text-align: center">

        {#        <h1 style="font-family#}

        <h1 style="font-family: 'Source Code Pro', monospace;">Method</h1>

        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <div calss="input-group mb-3 w-58 m-auto">
                <input type="text" class="form-control"
                       name="hello_world_input">

            </div>
            <input class="btn btn-dark rounded-pill px-4" type="submit">
            <input type="text" name="hello_world_input">

            <button class="btn btn-dark" type="submit">
                BUTTON
            </button>
        </form>

        {% if hello_world_list %}

            {% for hello_world in hello_world_list %}
                <h3>{{ hello_world.text }}</h3>
            {% endfor %}




            {#        {% if hello_world_output %}#}
            {##}
            {#        <h3>{{ hello_world_output.text }}</h3>#}
        {% endif %}

        {#    <div style="height: 20rem; background: antiquewhite; border-radius: 1rem; margin: 2rem; overflow: scroll;">#}
        {##}
        {#    <h1>Test, Test, Test</h1>#}

        {#    <div  class=testing style="display: block">block</div>#}
        {#    <div  class=testing style="display : inline">inline</div>#}
        {#    <div class="testing " style="display : inline-block">inline block</div>#}
        {#    <div  class=testing style="display : none">none</div>#}
        {#    <div class="testing">de</div>#}
        {##}
        {#    <div  class=testing style="display: block">block</div>#}
        {#    <div  class=testing style="display : inline">inline</div>#}
        {#    <div class="testing " style="display : inline-block">inline block</div>#}
        {#    <div  class=testing style="display : none">none</div>#}
        {#    <div class="testing">de</div>#}

        {#    <div  class=testing style="display: inline-block">block</div>#}
        {#    <div  class=testing style="display: inline-block; width: 3rem; height: 3rem">block</div>#}
        {#    <div  class=testing style="display: inline-block; width: 3em; height: 3em">block</div>#}
        {#    <div  class=testing style="display: inline-block; width: 30%; height: 30%">block</div>#}

    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>login</h4>
        </div>

        <div>
            <form action="{% url 'accountapp:login' %}" method='post'>
                {% csrf_token %}

                {% bootstrap_form form %}


                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
            </form>

        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/logout.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center">
        <div class="m-5">
            <h4>logout</h4>
        </div>

        <div>
            <form action="{% url 'accountapp:logout' %}" method='post'>
                {% csrf_token %}

                {{ form }}


                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
            </form>

        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>update info</h4>
        </div>

        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method='post'>
                {% csrf_token %}

                {% bootstrap_form form %}


                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
            </form>

        </div>
    </div>

{% endblock %}