accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name="create"),
    # 키를 받기위해서 int:pk사용
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

winwin_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),    #127.~~~/a
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html'%}

<body style="font-family:'NanumSquareR'">

{% include 'header.html'%}

<hr>

{% block content %}
{% endblock %}

<hr>

<div style="height: 10rem; background: antiquewhite; border-radius: 1rem; margin: 2rem;">

</div>

{% include 'footer.html'%}

</body>
</html>

templates/footer.html
<footer>
    <div style="text-align: center">
        <div style="font-size: .8rem; margin: 1.5rem">
            <span>공지사항/</span>
            <span>제휴문의/</span>
            <span>서비스소개/</span>
            <span>최정환 010-6530-1418</span>
        </div>
    </div>

    <div style="text-align: center">
        <h6>나는 뭐냐아</h6>
    </div>
</footer>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>김수민!!!!</title>

    {#부트스트랩 링크#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#    구글 폰트 링크 #}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fuggles&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fuggles&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Qahiri&display=swap" rel="stylesheet">

    {#    MATERIAL ICONS LINK#}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    {#    static file link#}
    <link rel="stylesheet" type="text/css" href={% static 'base.css' %}>

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align : center">


    <div>
        <h1 class="title">Why Come WoW</h1>
    </div>

    <div class="whycomewow_button">
        <span>
            <a href="{% url "accountapp:hello_world" %}">
                Home
            </a>
        </span>
        <span>nav2</span>

{#        로그인 되어있는사람한테만 보일수있도록#}
        {% if not user.is_authenticated %}

            <span>
            <a href="{% url "accountapp:login" %}">
                login
            </a>
        </span>
            <span>
            <a href="{% url "accountapp:create" %}">
                sign up
            </a>
        </span>

        {% else %}
            <span>
{#            단순라이팅을 하는게 아니라 정확히 번호를 넣어줘야한다. pk 값알받으므로 pk추가#}
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
            My Page
            </a>
        </span>

            <span>
            <a href="{% url 'accountapp:logout' %}">
            logout
            </a>
        </span>
        {% endif %}
    </div>

</div>
{#이파일을 통해..!!#}