articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView #템플릿을 보여주는가ㅓ

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView

app_name = 'articleapp'

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update')

]

# 라우팅 연결어~

winwin_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),    #127.~~~/a
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):
    #연결고리가 여러개로 되어있음 user랑 연결, CASCADE 알수없는 사용자가 데이터를적음..? 예전내용 가지고있음
    writer = models.ForeignKey(User,
                               on_delete=models.SET_NULL,
                               related_name='article',
                               null=True)

    title = models.CharField(max_length=200, null=True)
    #null=True는 없어도 괜찮다아

    image = models.ImageField(upload_to='article/', null=True)

    #CharFIeld보다 더 긴 텍스트를 사용할수있다아!!
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)


    ## 모델의 변화가 생겼기때문에 마이그래이션

articleapp/forms.py
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title','image', 'content']

articleapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView

from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)

class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

class ArticleUpdateView(UpdateView):
    model = Article
    form_clas = ArticleCreationForm
    context_object_name = 'target_article'
    # success_url = reverse_lazy('articleapp:list') 이걸 쓰지않고 오버라이딩 한다아아아!!

    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail',kwargs={'pk':self.object.pk})

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Create Article</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:create' %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %} 

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}


{% block content %}


    <div class="container">
        <div>
            {#      제목, 글쓴이, 작성일      #}
            <h1>{{ target_article.title }}</h1>
            <h3>{{ target_article.writer.profile.nickname }}</h3>
            <p>{{ target_article.created_at }}</p>
        </div>
        <div>
            {#      게시글 대표이미지, 글내용      #}
            <img src="{{ target_article.image.url }}" alt="">
            {{ target_article.content }}

            {# 업데이트와 연결시켜주는 것을 만들고 버튼을 만들자아 #}

            <div>
                <a href="{% url 'articleapp:update' pk=target_article.pk %}"
                class="btn btn-success round-pill px-5 red">
                    UUUUUUUpdate
                </a>
            </div>

        </div>
    </div>


{% endblock %} 

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container div {
          width: 280px;
          background-color: antiquewhite;
          display: flex;
          justify-content: center;
          align-items: center;
        }

        {#.container .item1 { height: 200px; }#}
        {#.container .item4 { height: 800px; }#}
        {#.container .item6 { height: 600px; }#}
        {#.container .item11 { height: 400px; }#}

        .container img{
            width : 100%;
            border-radius: 1rem;
        }

    </style>


    <div class="container my-4">
      <div class="item1">
          <img src="https://picsum.photos/200/300" alt="">
      </div>
      <div class="item2">
          <img src="https://picsum.photos/200/344" alt="">
      </div>
      <div class="item3">
          <img src="https://picsum.photos/200/254" alt="">
      </div>
      <div class="item4">
          <img src="https://picsum.photos/200/369" alt="">
      </div>
      <div class="item5">
          <img src="https://picsum.photos/200/300" alt="">
      </div>
      <div class="item6">
          <img src="https://picsum.photos/200/455" alt="">
      </div>
      <div class="item7">
          <img src="https://picsum.photos/200/230" alt="">
      </div>
      <div class="item8">
          <img src="https://picsum.photos/200/305" alt="">
      </div>
      <div class="item9">
          <img src="https://picsum.photos/200/400" alt="">
      </div>
      <div class="item10">
          <img src="https://picsum.photos/200/380" alt="">
      </div>
      <div class="item11">
          <img src="https://picsum.photos/200/360" alt="">
      </div>
      <div class="item12">
          <img src="https://picsum.photos/200/340" alt="">
      </div>
      <div class="item13">
          <img src="https://picsum.photos/200/320" alt="">
      </div>
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>


{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update update Article</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:update' pk=target_article.pk %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}